apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: development-gw
  namespace: cp4i
spec:
  version: 10.0.3.0
  license:
    accept: true
    use: nonproduction
    license: L-RJON-C2XKPU
  replicas: 3
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
  version: 10.0-cd
  users:
    - name: admin
      accessLevel: privileged
      passwordSecret: 'none'
