apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: production-gw
  namespace: cp4i
spec:
  license:
    accept: true
    use: production
    license: L-RJON-BYDR3Q
  replicas: 5
  resources:
    limits:
      memory: 16Gi
    requests:
      cpu: 8
      memory: 4Gi
  users:
    - name: admin
      accessLevel: privileged
      passwordSecret: 'none'
