apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: quick-gw
  namespace: cp4i
spec:
  version: 10.0.3.0
  license:
    accept: true
    use: nonproduction
    license: L-RJON-C2XKPU
  replicas: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  users:
    - name: admin
      accessLevel: privileged
      passwordSecret: admin-user-details
